# Utilisez une image de base appropriée pour votre application
FROM python:3.10

# Définition du répertoire de travail dans le conteneur
WORKDIR /app

# Copiez les fichiers nécessaires dans le conteneur
COPY app/main.py .

# Installez les dépendances de votre application
COPY requirements.txt .
RUN pip install -r requirements.txt

# Commande pour exécuter votre script
CMD [ "python", "main.py" ]
